/*
 * Java domain class for entity "ClaimLoginMaster" 
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.auth.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.auth.bean.LoginMasterID;
import com.maan.insurance.auth.bean.MarinLoginModel;
/**
 * <h2>ClaimLoginMasterRepository</h2>
 *
 * createdAt : 2022-05-14 - Time 15:00:24
 * <p>
 * Description: "ClaimLoginMaster" Repository
 */
 
 
 
public interface LoginMasterRepository  extends JpaRepository<MarinLoginModel,LoginMasterID > , JpaSpecificationExecutor<MarinLoginModel> {

	List<MarinLoginModel> findByLoginidLoginidAndLoginidPassword(String userId, String epass);
	
	MarinLoginModel findByLoginidLoginid(String loginId);



}
