/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:43:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.jpa.entity.facultative;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.maan.insurance.jpa.keys.TtrnFacRiskProposalKey;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "TtrnFacRiskProposal"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@IdClass(TtrnFacRiskProposalKey.class)
@Table(name="TTRN_FAC_RISK_PROPOSAL")


public class TtrnFacRiskProposal implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="RSK_PROPOSAL_NUMBER", nullable=false)
    private BigDecimal rskProposalNumber ;

    @Id
    @Column(name="RSK_ENDORSEMENT_NO", nullable=false)
    private BigDecimal rskEndorsementNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="NR", length=30)
    private String     nr ;

    @Column(name="MAXIMUM_LIMIT_OC", length=100)
    private String     maximumLimitOc ;

    @Column(name="MAXIMUM_LIMIT_DC")
    private BigDecimal maximumLimitDc ;

    @Column(name="DEDUCTIBLE_OC")
    private BigDecimal deductibleOc ;

    @Column(name="DEDUCTIBLE_DC")
    private BigDecimal deductibleDc ;

    @Column(name="SP_RETRO", length=4)
    private String     spRetro ;

    @Column(name="PML")
    private BigDecimal pml ;

    @Column(name="SI_PML_OC", length=20)
    private String     siPmlOc ;

    @Column(name="SI_PML_DC")
    private BigDecimal siPmlDc ;

    @Column(name="CU")
    private BigDecimal cu ;

    @Column(name="CU_RSN", length=500)
    private String     cuRsn ;

    @Column(name="SUM_INSURED_OC")
    private BigDecimal sumInsuredOc ;

    @Column(name="SUM_INSURED_DC")
    private BigDecimal sumInsuredDc ;

    @Column(name="GWPI_OC")
    private BigDecimal gwpiOc ;

    @Column(name="GWPI_DC")
    private BigDecimal gwpiDc ;

    @Column(name="PML_OC")
    private BigDecimal pmlOc ;

    @Column(name="PML_DC")
    private BigDecimal pmlDc ;

    @Column(name="TPL_OC")
    private BigDecimal tplOc ;

    @Column(name="TPL_DC")
    private BigDecimal tplDc ;

    @Column(name="SHARE_WRITTEN")
    private BigDecimal shareWritten ;

    @Column(name="SHARE_SIGNED")
    private BigDecimal shareSigned ;

    @Column(name="SUM_INSURED_OUR_SHARE_OC")
    private BigDecimal sumInsuredOurShareOc ;

    @Column(name="SUM_INSURED_OUR_SHARE_DC")
    private BigDecimal sumInsuredOurShareDc ;

    @Column(name="GWPI_OUR_SHARE_OC")
    private BigDecimal gwpiOurShareOc ;

    @Column(name="GWPI_OUR_SHARE_DC")
    private BigDecimal gwpiOurShareDc ;

    @Column(name="PML_OUR_SHARE_OC")
    private BigDecimal pmlOurShareOc ;

    @Column(name="PML_OUR_SHARE_DC")
    private BigDecimal pmlOurShareDc ;

    @Column(name="TPL_OUR_SHARE_OC")
    private BigDecimal tplOurShareOc ;

    @Column(name="TPL_OUR_SHARE_DC")
    private BigDecimal tplOurShareDc ;

    @Column(name="RISK_GRADE", length=30)
    private String     riskGrade ;

    @Column(name="OCCUPATION_CODE", length=500)
    private String     occupationCode ;

    @Column(name="RISK_DETAILS", length=1000)
    private String     riskDetails ;

    @Column(name="FIRE_PORT", length=30)
    private String     firePort ;

    @Column(name="SCOPE", length=30)
    private String     scope ;

    @Column(name="MB_IND", length=4)
    private String     mbInd ;

    @Column(name="CATEGORY_ZONE", length=30)
    private String     categoryZone ;

    @Column(name="EARTHQUAKE_WS_IND", length=10)
    private String     earthquakeWsInd ;

    @Column(name="WS_THREAT_IND", length=30)
    private String     wsThreatInd ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_ENTRY_DATE")
    private Date       rskEntryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_END_DATE")
    private Date       rskEndDate ;

    @Column(name="RSK_STATUS", length=4)
    private String     rskStatus ;

    @Column(name="RSK_REMARKS", length=100)
    private String     rskRemarks ;

    @Column(name="RSK_CEDANT_RETENTION")
    private BigDecimal rskCedantRetention ;

    @Column(name="RSK_INTEREST", length=500)
    private String     rskInterest ;

    @Column(name="EQ_THREAT", length=10)
    private String     eqThreat ;

    @Column(name="NO_OF_INSURERS")
    private BigDecimal noOfInsurers ;

    @Column(name="RSK_CEDRET_TYPE", length=1)
    private String     rskCedretType ;

    @Column(name="DEDUCTIBLE_FACXOL_OC")
    private BigDecimal deductibleFacxolOc ;

    @Column(name="DEDUCTIBLE_FACXOL_DC")
    private BigDecimal deductibleFacxolDc ;

    @Column(name="XOL_OC")
    private BigDecimal xolOc ;

    @Column(name="XOL_DC")
    private BigDecimal xolDc ;

    @Column(name="XOL_OURSHARE_OC")
    private BigDecimal xolOurshareOc ;

    @Column(name="XOL_OURSHARE_DC")
    private BigDecimal xolOurshareDc ;

    @Column(name="MND_INSTALLMENTS")
    private BigDecimal mndInstallments ;

    @Column(name="M_LOP", length=1)
    private String     mLop ;

    @Column(name="A_LOP", length=1)
    private String     aLop ;

    @Column(name="MODE_TRANSPORT_ID")
    private BigDecimal modeTransportId ;

    @Column(name="VESSEL_NAME", length=200)
    private String     vesselName ;

    @Column(name="VESSEL_AGE")
    private BigDecimal vesselAge ;

    @Column(name="LIMIT_PER_VESSEL_OC")
    private BigDecimal limitPerVesselOc ;

    @Column(name="LIMIT_PER_VESSEL_DC")
    private BigDecimal limitPerVesselDc ;

    @Column(name="LIMIT_PER_LOCATION_OC")
    private BigDecimal limitPerLocationOc ;

    @Column(name="LIMIT_PER_LOCATION_DC")
    private BigDecimal limitPerLocationDc ;

    @Column(name="TYPE", length=5)
    private String     type ;

    @Column(name="DEDUCTIBLE_OURSHARE_OC")
    private BigDecimal deductibleOurshareOc ;

    @Column(name="DEDUCTIBLE_OURSHARE_DC")
    private BigDecimal deductibleOurshareDc ;

    @Column(name="DEDUCTIBLE_FACXOL_OURSHARE_OC")
    private BigDecimal deductibleFacxolOurshareOc ;

    @Column(name="DEDUCTIBLE_FACXOL_OURSHARE_DC")
    private BigDecimal deductibleFacxolOurshareDc ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SYS_DATE")
    private Date       sysDate ;

    @Column(name="COVER_LIMIT_PML_OC")
    private BigDecimal coverLimitPmlOc ;

    @Column(name="COVER_LIMIT_PML_DC")
    private BigDecimal coverLimitPmlDc ;

    @Column(name="GWPI_PML_OC")
    private BigDecimal gwpiPmlOc ;

    @Column(name="GWPI_PML_DC")
    private BigDecimal gwpiPmlDc ;

    @Column(name="PSL_OC")
    private BigDecimal pslOc ;

    @Column(name="PSL_DC")
    private BigDecimal pslDc ;

    @Column(name="PSL_OS_OC")
    private BigDecimal pslOsOc ;

    @Column(name="PSL_OS_DC")
    private BigDecimal pslOsDc ;

    @Column(name="PLL_OC")
    private BigDecimal pllOc ;

    @Column(name="PLL_DC")
    private BigDecimal pllDc ;

    @Column(name="PLL_OS_OC")
    private BigDecimal pllOsOc ;

    @Column(name="PLL_OS_DC")
    private BigDecimal pllOsDc ;

    @Column(name="PBL_OC")
    private BigDecimal pblOc ;

    @Column(name="PBL_DC")
    private BigDecimal pblDc ;

    @Column(name="PBL_OS_OC")
    private BigDecimal pblOsOc ;

    @Column(name="PBL_OS_DC")
    private BigDecimal pblOsDc ;

    @Column(name="PML_OS_OC")
    private BigDecimal pmlOsOc ;

    @Column(name="PML_OS_DC")
    private BigDecimal pmlOsDc ;

    @Column(name="PML_100_OC")
    private BigDecimal pml100Oc ;

    @Column(name="PML_100_DC")
    private BigDecimal pml100Dc ;

    @Column(name="SUM_INS_PML_OC")
    private BigDecimal sumInsPmlOc ;

    @Column(name="SUM_INS_PML_DC")
    private BigDecimal sumInsPmlDc ;

    @Column(name="SUM_INS_PML_OS_OC")
    private BigDecimal sumInsPmlOsOc ;

    @Column(name="SUM_INS_PML_OS_DC")
    private BigDecimal sumInsPmlOsDc ;

    @Column(name="COVER_LIMIT_PML_OS_OC")
    private BigDecimal coverLimitPmlOsOc ;

    @Column(name="COVER_LIMIT_PML_OS_DC")
    private BigDecimal coverLimitPmlOsDc ;

    @Column(name="GWPI_PML_OS_OC")
    private BigDecimal gwpiPmlOsOc ;

    @Column(name="GWPI_PML_OS_DC")
    private BigDecimal gwpiPmlOsDc ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



