/*
 * Java domain class for entity "TtrnRiskProposal" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:16 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:44:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.jpa.repository.propPremium;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.jpa.entity.propPremium.TtrnDepositRelease;
import com.maan.insurance.model.entity.TtrnDepositReleaseId;
/**
 * <h2>TtrnRiskProposalRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:44:16
 * <p>
 * Description: "TtrnRiskProposal" Repository
 */
 
 
 
public interface TtrnDepositReleaseRepository  extends JpaRepository<TtrnDepositRelease,TtrnDepositReleaseId > , JpaSpecificationExecutor<TtrnDepositRelease> {

	TtrnDepositRelease findByContractNoAndTempRequestNo(String contractNo, BigDecimal bigDecimal);

//	TtrnDepositRelease findTop1ByBranchCodeOrderByRlNoDesc(String branchCode);

	List<TtrnDepositRelease> findByBranchCodeOrderByRlNoDesc(String branchCode);

	List<TtrnDepositRelease> findTop1ByBranchCodeOrderByRlNoDesc(String branchCode);

}
