/*
 *  Copyright (c) 2019. All right reserved
 * Created on 2021-11-19 ( Date ISO 2021-11-19 - Time 13:16:53 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2021-11-19 ( 13:16:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.insurance.notification.req;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Domain class for entity "SmsConfigMaster"
 *
 * @author Telosys Tools Generator
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class SmsGetReq {

@JsonProperty("MobileNo")
private String mobileNo;
}
