package com.maan.insurance.jpa.entity.treasury;

/* 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:41:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */




import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.maan.insurance.jpa.keys.BankMasterKey;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "BankMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@IdClass(BankMasterKey.class)
@Table(name="BANK_MASTER")

public class BankMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BANK_ID", nullable=false)
    private Integer bankId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BANK_NAME", length=500)
    private String     bankName ;

    @Column(name="BANK_AC_NO", nullable=false)
    private BigDecimal bankAcNo ;

    @Column(name="BANK_CURRENCY", length=1000)
    private String     bankCurrency ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Column(name="REMARKS", length=1000)
    private String     remarks ;

    @Column(name="BANK_ADDRESS", length=100)
    private String     bankAddress ;

    @Column(name="BANK_ACCOUNT_NAME", length=500)
    private String     bankAccountName ;

    @Column(name="IBAN", length=500)
    private String     iban ;

    @Column(name="SWIFT_CODE", length=500)
    private String     swiftCode ;

    @Column(name="CORRES_BANK1_NAME", length=500)
    private String     corresBank1Name ;

    @Column(name="CORRES_BANK1_ACCOUNT_NO", length=500)
    private String     corresBank1AccountNo ;

    @Column(name="CORRES_BANK1_ADDRESS", length=500)
    private String     corresBank1Address ;

    @Column(name="CORRES_BANK1_SWIFTCODE", length=500)
    private String     corresBank1Swiftcode ;

    @Column(name="CORRES_BANK2_NAME", length=500)
    private String     corresBank2Name ;

    @Column(name="CORRES_BANK2_ACCOUNT_NO", length=500)
    private String     corresBank2AccountNo ;

    @Column(name="CORRES_BANK2_ADDRESS", length=500)
    private String     corresBank2Address ;

    @Column(name="CORRES_BANK2_SWIFTCODE", length=500)
    private String     corresBank2Swiftcode ;

    @Column(name="COA_ID", length=500)
    private String     coaId ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



