/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-05 ( Date ISO 2022-01-05 - Time 16:11:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-05 ( 16:11:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.insurance.notification.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Domain class for entity "MailMaster"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class MailMasterRes implements Serializable {

	private static final long serialVersionUID = 1L;

	@JsonProperty("InsCompanyId")
	private String insCompanyId;

	@JsonProperty("SmtpHost")
	private String smtpHost;

	@JsonProperty("SmtpUser")
	private String smtpUser;

	@JsonProperty("SmtpPwd")
	private String smtpPwd;

	@JsonProperty("Address")
	private String address;

	@JsonProperty("Status")
	private String status;

	@JsonProperty("Remarks")
	private String remarks;

	@JsonProperty("SmtpPort")
	private Integer smtpPort;

	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("Entrydate")
	private Date entrydate;

}
