/*
 * Java domain class for entity "NotifTemplateMaster"
 * Created on 2021-10-01 ( Date ISO 2021-10-01 - Time 11:40:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2021-10-01 ( 11:40:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.notification.repo;

import java.util.Date;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.notification.entity.NotifTemplateMaster;
import com.maan.insurance.notification.entity.NotifTemplateMasterId;

/**
 * <h2>NotifTemplateMasterRepository</h2>
 * <p>
 * createdAt : 2021-10-01 - Time 11:40:29
 * <p>
 * Description: "NotifTemplateMaster" Repository
 */


public interface NotifTemplateMasterRepository extends JpaRepository<NotifTemplateMaster, NotifTemplateMasterId>, JpaSpecificationExecutor<NotifTemplateMaster> {


	List<NotifTemplateMaster> findByMailRequiredAndStatusAndNotificationApplicableAndInsIdOrderByMailSubjectAsc(String string, String string2, String notifApplicable, String insId);

	List<NotifTemplateMaster> findBySmsRequiredAndStatusAndNotificationApplicableAndInsIdOrderBySmsSubjectAsc(String string, String string2, String notifApplicable, String insId);

	List<NotifTemplateMaster> findByInsIdOrderByEntryDateDesc(String insId);
	
	Integer countByInsIdOrderByEntryDateDesc(String insId);
	
	List<NotifTemplateMaster> findBySnoAndStatusAndNotificationApplicableAndInsIdAndEffectiveDateLessThanEqualOrderByEntryDateDesc(Integer sno, String string,String notificationApplicable,String insId, Date date);
	
	List<NotifTemplateMaster> findByStatusAndNotificationApplicableAndEffectiveDateLessThanEqualOrderByEntryDateDesc(String string, String notifTemplateId, Date today);

	List<NotifTemplateMaster> findBySnoAndInsIdAndQueryKeyAndEffectiveDateBetweenOrderByAmendidDesc(Integer sno,String insId,String queryKey,Date effectiveDatefrom,Date effectiveDateto);

	Optional<NotifTemplateMaster> findBySnoAndInsIdAndQueryKeyOrderByEntryDateDesc(Integer sno, String insId,String queryKey);

	
}
