/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:05 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:44:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.jpa.entity.propPremium;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "TtrnRetroCessionary"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TtrnRetroCessionaryId.class)
@Table(name="TTRN_RETRO_CESSIONARY")


public class TtrnRetroCessionary implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="SNO", nullable=false)
    private BigDecimal sno ;

    @Id
    @Column(name="PROPOSAL_NO", nullable=false, length=35)
    private String     proposalNo ;

    @Id
    @Column(name="CONTRACT_NO", nullable=false, length=30)
    private String     contractNo ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CEDING_COMPANY_ID")
    private BigDecimal cedingCompanyId ;

    @Column(name="BROKER_ID")
    private BigDecimal brokerId ;

    @Column(name="SHARE_ACCEPTED")
    private BigDecimal shareAccepted ;

    @Column(name="SHARE_SIGNED")
    private BigDecimal shareSigned ;

    @Column(name="COMISSION")
    private BigDecimal comission ;

    @Column(name="PROPOSAL_STATUS", length=1)
    private String     proposalStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=250)
    private String     remarks ;

    @Column(name="LAYER_NO")
    private BigDecimal layerNo ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



