/*
 * Created on 2022-09-15 ( 15:44:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.insurance.jpa.entity.propPremium;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "TtrnRetroCessionary" ( stored in table "TTRN_RETRO_CESSIONARY" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TtrnRetroCessionaryId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal sno ;
    
    private String     proposalNo ;
    
    private String     contractNo ;
    
    private BigDecimal amendId ;
    
     
}
