/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:32 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:43:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.jpa.entity.propPremium;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "TtrnInsurerDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TtrnInsurerDetailsId.class)
@Table(name="TTRN_INSURER_DETAILS")


public class TtrnInsurerDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="INSURER_NO", nullable=false)
    private BigDecimal insurerNo ;

    @Id
    @Column(name="PROPOSAL_NO", nullable=false, length=20)
    private String     proposalNo ;

    @Id
    @Column(name="ENDORSEMENT_NO", nullable=false)
    private BigDecimal endorsementNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CONTRACT_NO", length=20)
    private String     contractNo ;

    @Column(name="CEDING_ID")
    private BigDecimal cedingId ;

    @Column(name="RETRO_PERCENTAGE")
    private BigDecimal retroPercentage ;

    @Column(name="STATUS", length=4)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE")
    private Date       endDate ;

    @Column(name="REMARKS", length=50)
    private String     remarks ;

    @Column(name="TYPE", length=1)
    private String     type ;

    @Column(name="UW_YEAR", length=20)
    private String     uwYear ;

    @Column(name="RETRO_TYPE", length=10)
    private String     retroType ;

    @Column(name="SUB_CLASS")
    private BigDecimal subClass ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



