/*
 * Created on 2022-09-15 ( 15:43:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.insurance.jpa.keys;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "TtrnCashLossCreditUpdate" ( stored in table "TTRN_CASH_LOSS_CREDIT_UPDATE" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class TtrnCashLossCreditUpdateKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     contractNo ;
    
    private BigDecimal transactionNo ;
    
    private BigDecimal claimNo ;
    
    private BigDecimal amendId ;
    
     
}
