/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-05 ( Date ISO 2022-01-05 - Time 16:11:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-05 ( 16:11:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.notification.entity;


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "MailMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MAIL_MASTER")


public class MailMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APP_ID", nullable=false)
    private String     appId;

    //--- ENTITY DATA FIELDS 
    @Column(name="SMTP_HOST", length=50)
    private String     smtpHost ;

    @Column(name="SMTP_USER", length=25)
    private String     smtpUser ;

    @Column(name="SMTP_PWD", length=10)
    private String     smtpPwd ;


    @Column(name="EXP_TIME")
    private String     expTime ;

    @Column(name="HOME_APP")
    private String     homeApp ;

    @Column(name="LOGO_PATH")
    private String     logoPath ;

    @Column(name="SMTP_PORT")
    private String smtpPort ;

    @Column(name="ENTRYDATE")
    private String       entrydate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @Column(name="MAIL_CC")
    private String     mailCc ;

    @Column(name="PWD_CNT")
    private String     pwdCnt ;

    @Column(name="PWD_LEN")
    private String     pwdLen ;

    @Column(name="SMTP_ADDRESS")
    private String smtpAddress ;
    
    @Column(name="SMTP_SHORT_ADDRESS")
    private String smtpShortAddress ;

}



