/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:55 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.jpa.entity.xolpremium;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.maan.insurance.jpa.keys.TtrnMndInstallmentsKey;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "TtrnMndInstallments"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@IdClass(TtrnMndInstallmentsKey.class)
@Table(name="TTRN_MND_INSTALLMENTS")


public class TtrnMndInstallments implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="INSTALLMENT_NO", nullable=false)
    private BigDecimal installmentNo ;

    @Id
    @Column(name="PROPOSAL_NO", nullable=false, length=35)
    private String     proposalNo ;

    @Id
    @Column(name="CONTRACT_NO", nullable=false, length=30)
    private String     contractNo ;

    @Id
    @Column(name="ENDORSEMENT_NO", nullable=false)
    private BigDecimal endorsementNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="LAYER_NO")
    private BigDecimal layerNo ;

    @Column(name="INSTALLMENT_DATE")
    private Date       installmentDate ;

    @Column(name="MND_PREMIUM_OC")
    private BigDecimal mndPremiumOc ;

    @Column(name="MND_PREMIUM_DC")
    private BigDecimal mndPremiumDc ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="PAYEMENT_DUE_DAY", length=20)
    private String     payementDueDay ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="TRANSACTION_NO")
    private BigDecimal transactionNo ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



