/*
 * Java domain class for entity "CompanyMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:41:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.CompanyMaster;
import com.maan.insurance.model.entity.CompanyMasterId;
/**
 * <h2>CompanyMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:41:29
 * <p>
 * Description: "CompanyMaster" Repository
 */
 
 
 
public interface CompanyMasterRepository  extends JpaRepository<CompanyMaster,CompanyMasterId > , JpaSpecificationExecutor<CompanyMaster> {

}
