/*
 * Java domain class for entity "ConstantDetail" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:41:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.ConstantDetail;
import com.maan.insurance.model.entity.ConstantDetailId;
/**
 * <h2>ConstantDetailRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:41:30
 * <p>
 * Description: "ConstantDetail" Repository
 */
 
 
 
public interface ConstantDetailRepository  extends JpaRepository<ConstantDetail,ConstantDetailId > , JpaSpecificationExecutor<ConstantDetail> {

	List<ConstantDetail> findByCategoryIdAndStatusAndCategoryDetailId(BigDecimal bigDecimal, String string2,
			BigDecimal bigDecimal2);

	List<ConstantDetail> findByCategoryId(BigDecimal bigDecimal);

	List<ConstantDetail> findByCategoryIdAndBranchCodeOrderByCategoryDetailId(BigDecimal bigDecimal, String branchCode);

	List<ConstantDetail> findDistinctByCategoryIdAndStatusOrderByType(BigDecimal bigDecimal, String string);


	List<ConstantDetail> findDistinctByCategoryIdAndStatus(BigDecimal bigDecimal, String string);

	List<ConstantDetail> findByCategoryIdAndStatus(BigDecimal bigDecimal, String string);

}
