/*
 * Java domain class for entity "CurrencyMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:41:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.CurrencyMaster;
import com.maan.insurance.model.entity.CurrencyMasterId;
/**
 * <h2>CurrencyMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:41:34
 * <p>
 * Description: "CurrencyMaster" Repository
 */
 
 
 
public interface CurrencyMasterRepository  extends JpaRepository<CurrencyMaster,CurrencyMasterId > , JpaSpecificationExecutor<CurrencyMaster> {

}
