/*
 * Java domain class for entity "PersonalInfo" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:41:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.PersonalInfo;
import com.maan.insurance.model.entity.PersonalInfoId;
/**
 * <h2>PersonalInfoRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:41:51
 * <p>
 * Description: "PersonalInfo" Repository
 */
 
 
 
public interface PersonalInfoRepository  extends JpaRepository<PersonalInfo,PersonalInfoId > , JpaSpecificationExecutor<PersonalInfo> {

}
