/*
 * Java domain class for entity "PositionMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.PositionMaster;
import com.maan.insurance.model.entity.PositionMasterId;
/**
 * <h2>PositionMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:02
 * <p>
 * Description: "PositionMaster" Repository
 */
 
 
 
public interface PositionMasterRepository  extends JpaRepository<PositionMaster,PositionMasterId > , JpaSpecificationExecutor<PositionMaster> {

	PositionMaster findByProposalNoAndAmendId(BigDecimal bigDecimal, BigDecimal bigDecimal2);

	PositionMaster findByProposalNo(BigDecimal bigDecimal);

	PositionMaster findByProposalNoAndContractStatus(BigDecimal bigDecimal, String string);

	List<PositionMaster> findDistinctByBranchCodeAndBouquetNoNotNull(String branchCode);

}
