/*
 * Java domain class for entity "RskPremiumDetails" 
 * Created on 2022-10-17 ( Date ISO 2022-10-17 - Time 18:04:31 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-10-17 ( 18:04:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.maan.insurance.model.entity.RskPremiumDetails;
/**
 * <h2>RskPremiumDetailsRepository</h2>
 *
 * createdAt : 2022-10-17 - Time 18:04:31
 * <p>
 * Description: "RskPremiumDetails" Repository
 */
 
 
 @Repository
public interface RskPremiumDetailsRepository  extends JpaRepository<RskPremiumDetails,Long>, JpaSpecificationExecutor<RskPremiumDetails> {

	List<RskPremiumDetails> findByContractNo(Long contractNo);
	
	long countByContractNoAndLayerNo(BigDecimal bigDecimal, BigDecimal valueOf);

	RskPremiumDetails findByContractNoAndTransactionNo(BigDecimal bigDecimal, BigDecimal bigDecimal2);

	List<RskPremiumDetails> findByLoginIdAndBranchCodeAndContractNoAndTransactionNo(String loginId, String branchCode,
			BigDecimal bigDecimal, BigDecimal bigDecimal2);

	RskPremiumDetails findByContractNoAndRequestNo(BigDecimal bigDecimal, BigDecimal bigDecimal2);

	RskPremiumDetails findByRequestNoAndBranchCode(BigDecimal bigDecimal, String branchCode);

	int countByContractNo(BigDecimal contractNo);

}
