/*
 * Java domain class for entity "TmasBranchMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TmasBranchMaster;
/**
 * <h2>TmasBranchMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:23
 * <p>
 * Description: "TmasBranchMaster" Repository
 */
 
 
 
public interface TmasBranchMasterRepository  extends JpaRepository<TmasBranchMaster,String > , JpaSpecificationExecutor<TmasBranchMaster> {

	TmasBranchMaster findByBranchCode(String branchCode);

}
