/*
 * Java domain class for entity "TmasDepartmentMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.maan.insurance.model.entity.TmasDepartmentMaster;
import com.maan.insurance.model.entity.TmasDepartmentMasterId;

/**
 * <h2>TmasDepartmentMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:26
 * <p>
 * Description: "TmasDepartmentMaster" Repository
 */
 
 
 @Repository
public interface TmasDepartmentMasterRepository  extends JpaRepository<TmasDepartmentMaster,TmasDepartmentMasterId> , JpaSpecificationExecutor<TmasDepartmentMaster> {


	List<TmasDepartmentMaster> findByBranchCodeAndTmasProductIdAndTmasStatusAndCoreCompanyCodeIsNotNullAndTmasDepartmentIdIn(
			String branchCode, BigDecimal valueOf, String string, List<BigDecimal> departIdList);
	
	long countByBranchCodeAndTmasProductIdAndTmasStatusAndCoreCompanyCodeIsNotNullAndTmasDepartmentIdIn(
			String branchCode, BigDecimal bigDecimal, String string, List<BigDecimal> departmentId);

	List<TmasDepartmentMaster> findByTmasStatusAndTmasProductIdAndBranchCodeOrderByTmasDepartmentNameAsc(String string,
			BigDecimal bigDecimal, String branchCode);

	List<TmasDepartmentMaster> findByTmasProductIdAndBranchCodeAndTmasStatusOrderByTmasDepartmentName(BigDecimal bigDecimal,
			String branchCode, String string);

	TmasDepartmentMaster findByBranchCodeAndTmasProductIdAndTmasDepartmentIdAndTmasStatus(String branchCode,
			BigDecimal bigDecimal, BigDecimal bigDecimal2, String string);



	TmasDepartmentMaster findByBranchCodeAndTmasProductIdAndTmasStatusAndCoreCompanyCodeNotNullAndTmasDepartmentIdIn(
			String branchCode, BigDecimal bigDecimal, String string, List<BigDecimal> dept1);

	List<TmasDepartmentMaster> findDistinctByBranchCodeAndTmasProductIdAndTmasStatusOrderByTmasDepartmentNameAsc(
			String branchCode, BigDecimal bigDecimal, String status);

}
