/*
 * Java domain class for entity "TmasSpfcMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:46 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TmasSpfcMaster;
import com.maan.insurance.model.entity.TmasSpfcMasterId;
/**
 * <h2>TmasSpfcMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:46
 * <p>
 * Description: "TmasSpfcMaster" Repository
 */
 
 
 
public interface TmasSpfcMasterRepository  extends JpaRepository<TmasSpfcMaster,TmasSpfcMasterId > , JpaSpecificationExecutor<TmasSpfcMaster> {



	List<TmasSpfcMaster> findDistinctByBranchCodeAndTmasProductIdAndTmasStatusAndTmasDepartmentIdAndTmasSpfcIdInOrderByTmasSpfcNameAsc(
			String branchCode, BigDecimal bigDecimal, String string, BigDecimal bigDecimal2, List<String> spfcId);

	List<TmasSpfcMaster> findDistinctByBranchCodeAndTmasProductIdAndTmasStatusAndTmasDepartmentIdOrderByTmasSpfcNameAsc(
			String branchCode, BigDecimal bigDecimal, String string, BigDecimal bigDecimal2);

	List<TmasSpfcMaster> findDistinctByBranchCodeAndTmasProductIdAndTmasStatusAndTmasSpfcIdInOrderByTmasSpfcNameAsc(
			String branchCode, BigDecimal bigDecimal, String string, List<String> spfcId);

}
