/*
 * Java domain class for entity "TmasPolicyBranch" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:39 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TmasPolicyBranch;
import com.maan.insurance.model.entity.TmasPolicyBranchId;
/**
 * <h2>TmasPolicyBranchRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:39
 * <p>
 * Description: "TmasPolicyBranch" Repository
 */
 
 
 
public interface TmasPolicyBranchRepository  extends JpaRepository<TmasPolicyBranch,TmasPolicyBranchId > , JpaSpecificationExecutor<TmasPolicyBranch> {

	List<TmasPolicyBranch> findDistinctByBranchCodeAndTmasStatusOrderByTmasPolBranchNameAsc(String branchCode,
			String string);

}
