/*
 * Java domain class for entity "TmasLoginDetails" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:31 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TmasLoginDetails;
import com.maan.insurance.model.entity.TmasLoginDetailsId;
/**
 * <h2>TmasLoginDetailsRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:31
 * <p>
 * Description: "TmasLoginDetails" Repository
 */
 
 
 
public interface TmasLoginDetailsRepository  extends JpaRepository<TmasLoginDetails,TmasLoginDetailsId > , JpaSpecificationExecutor<TmasLoginDetails> {

	List<TmasLoginDetails> findByLoginIdAndActive(String userId, String string);

}
