/*
 * Java domain class for entity "TmasPfcMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:38 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:42:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TmasPfcMaster;
import com.maan.insurance.model.entity.TmasPfcMasterId;
/**
 * <h2>TmasPfcMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:42:38
 * <p>
 * Description: "TmasPfcMaster" Repository
 */
 
 
 
public interface TmasPfcMasterRepository  extends JpaRepository<TmasPfcMaster,TmasPfcMasterId > , JpaSpecificationExecutor<TmasPfcMaster> {

	List<TmasPfcMaster> findDistinctByBranchCodeAndTmasStatusOrderByTmasPfcNameAsc(String branchCode, String string);

}
