/*
 * Java domain class for entity "TtrnClaimPayment" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:17 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:43:17 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TtrnClaimPayment;
import com.maan.insurance.model.entity.TtrnClaimPaymentId;
/**
 * <h2>TtrnClaimPaymentRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:43:17
 * <p>
 * Description: "TtrnClaimPayment" Repository
 */
 
 
 
public interface TtrnClaimPaymentRepository  extends JpaRepository<TtrnClaimPayment,TtrnClaimPaymentId > , JpaSpecificationExecutor<TtrnClaimPayment> {

	TtrnClaimPayment findByContractNoAndClaimPaymentNo(String contractNo, BigDecimal bigDecimal);

	Long countByClaimNoAndContractNo(BigDecimal valueOf, String contNo);

}
