/*
 * Java domain class for entity "TtrnMndInstallments" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:43:55 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.jpa.entity.xolpremium.TtrnMndInstallments;
import com.maan.insurance.jpa.keys.TtrnMndInstallmentsKey;
/**
 * <h2>TtrnMndInstallmentsRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:43:55
 * <p>
 * Description: "TtrnMndInstallments" Repository
 */
 
 
 
public interface TtrnMndInstallmentsRepository  extends JpaRepository<TtrnMndInstallments,TtrnMndInstallmentsKey > , JpaSpecificationExecutor<TtrnMndInstallments> {


	List<TtrnMndInstallments> findByProposalNoAndLayerNoAndEndorsementNoAndEndorsementNoNotNullOrderByInstallmentNoAsc(
			String proposalNo, BigDecimal bigDecimal, BigDecimal bigDecimal2);

	int countByProposalNoAndInstallmentNoAndEndorsementNo(String proposalNo, BigDecimal bigDecimal,
			BigDecimal bigDecimal2);

	TtrnMndInstallments findByInstallmentNoAndProposalNoAndEndorsementNo(BigDecimal bigDecimal, String proposalNo,
			BigDecimal bigDecimal2);

	TtrnMndInstallments findByProposalNoAndEndorsementNo(String proposalNo, BigDecimal bigDecimal);

	TtrnMndInstallments findByProposalNo(String proposalNo);

}
