/*
 * Java domain class for entity "TtrnRiskCommission" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:13 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:44:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.TtrnRiskCommission;
import com.maan.insurance.model.entity.TtrnRiskCommissionId;
/**
 * <h2>TtrnRiskCommissionRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:44:13
 * <p>
 * Description: "TtrnRiskCommission" Repository
 */
 
 
 
public interface TtrnRiskCommissionRepository  extends JpaRepository<TtrnRiskCommission,TtrnRiskCommissionId > , JpaSpecificationExecutor<TtrnRiskCommission> {


	List<TtrnRiskCommission> findTop1ByRskProposalNumberOrderByRskEndorsementNoDesc(String proposalNo);

	TtrnRiskCommission findByRskProposalNumberAndRskEndorsementNo(String proposalNo, BigDecimal bigDecimal);

}
