/*
 * Java domain class for entity "TtrnRetroCessionary" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:05 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:44:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.jpa.entity.propPremium.TtrnRetroCessionary;
import com.maan.insurance.jpa.entity.propPremium.TtrnRetroCessionaryId;
/**
 * <h2>TtrnRetroCessionaryRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:44:05
 * <p>
 * Description: "TtrnRetroCessionary" Repository
 */
 
 
 
public interface TtrnRetroCessionaryRepository  extends JpaRepository<TtrnRetroCessionary,TtrnRetroCessionaryId > , JpaSpecificationExecutor<TtrnRetroCessionary> {

	Long countByProposalNo(String proposalNo);

	int countByProposalNoAndSnoAndAmendId(String proposalNo, BigDecimal bigDecimal,
			BigDecimal bigDecimal2);

}
