/*
 * Java domain class for entity "UnderwritterMaster" 
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-09-15 ( 15:44:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.insurance.model.entity.UnderwritterMaster;
import com.maan.insurance.model.entity.UnderwritterMasterId;
/**
 * <h2>UnderwritterMasterRepository</h2>
 *
 * createdAt : 2022-09-15 - Time 15:44:23
 * <p>
 * Description: "UnderwritterMaster" Repository
 */
 
 
 
public interface UnderwritterMasterRepository  extends JpaRepository<UnderwritterMaster,UnderwritterMasterId > , JpaSpecificationExecutor<UnderwritterMaster> {


//	String findByBranchCodeAndUwrStatusAndUnderwritterIsContaining(String branchCode, String string, String value);


	List<UnderwritterMaster> findByBranchCodeAndUwrStatusAndUnderwritterIgnoreCaseContaining(String branchCode,
			String string, String underwriterSearch);

}
