/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:41:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "CompanyMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CompanyMasterId.class)
@Table(name="COMPANY_MASTER")


public class CompanyMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COMPANY_CODE", nullable=false, length=100)
    private String     companyCode ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SNO")
    private BigDecimal sno ;

    @Column(name="TITLE", length=10)
    private String     title ;

    @Column(name="COMPANY_NAME", length=200)
    private String     companyName ;

    @Column(name="TELEPHONE", length=20)
    private String     telephone ;

    @Column(name="MOBILE", length=20)
    private String     mobile ;

    @Column(name="FAX", length=20)
    private String     fax ;

    @Column(name="EMAIL", length=100)
    private String     email ;

    @Column(name="POBOX", length=25)
    private String     pobox ;

    @Column(name="ADDRESS1", length=500)
    private String     address1 ;

    @Column(name="ADDRESS2", length=150)
    private String     address2 ;

    @Column(name="CITY", length=200)
    private String     city ;

    @Column(name="COUNTRY", length=100)
    private String     country ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="BASE_CURRENCY", length=20)
    private String     baseCurrency ;

    @Column(name="DEST_CURRENCY", length=20)
    private String     destCurrency ;

    @Column(name="FINANCIAL_YEAR", length=20)
    private String     financialYear ;

    @Column(name="BAND_REPORT", length=20)
    private String     bandReport ;

    @Column(name="CURRENCY_DECIMAL")
    private BigDecimal currencyDecimal ;

    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="WEB_SITE", length=200)
    private String     webSite ;

    @Column(name="HEADER_LOGO", length=100)
    private String     headerLogo ;

    @Column(name="MAIN_LOGO", length=100)
    private String     mainLogo ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



