/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:41:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:41:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "ConstantDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ConstantDetailId.class)
@Table(name="CONSTANT_DETAIL")


public class ConstantDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CATEGORY_ID", nullable=false)
    private BigDecimal categoryId ;

    @Id
    @Column(name="CATEGORY_DETAIL_ID", nullable=false)
    private BigDecimal categoryDetailId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DETAIL_NAME", length=300)
    private String     detailName ;

    @Column(name="REMARKS", length=170)
    private String     remarks ;

    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="CORE_APP_CODE", length=25)
    private String     coreAppCode ;

    @Column(name="PERCENT")
    private BigDecimal percent ;

    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Column(name="TYPE", length=20)
    private String     type ;

    @Column(name="PARAM1", length=100)
    private String     param1 ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



