/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:20 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "TerritoryMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TerritoryMasterId.class)
@Table(name="TERRITORY_MASTER")


public class TerritoryMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="TERRITORY_CODE", nullable=false, length=30)
    private String     territoryCode ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="TERRITORY_ID")
    private BigDecimal territoryId ;

    @Column(name="TERRITORY_DESCR", length=30)
    private String     territoryDescr ;

    @Column(name="TERRITORY_STATUS", length=1)
    private String     territoryStatus ;

    @Column(name="CORE_COMPANY_CODE", length=20)
    private String     coreCompanyCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



