/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:22 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "TmasBranchMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="TMAS_BRANCH_MASTER")


public class TmasBranchMaster implements Serializable {
 
private static final long serialVersionUID = 1L; 
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=10)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BRANCH_NAME", length=100)
    private String     branchName ;

    @Column(name="BASE_CURRENCY_ID")
    private BigDecimal baseCurrencyId ;

    @Column(name="DESC_CURRENCY_ID")
    private BigDecimal descCurrencyId ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="COUNTRY_ID")
    private BigDecimal countryId ;

    @Column(name="CORE_APP_CODE", length=20)
    private String     coreAppCode ;

    @Column(name="COMPANY_CODE", length=30)
    private String     companyCode ;

    @Column(name="COUNTRY_SHORT_NAME", length=10)
    private String     countryShortName ;

   // @Column(name="VAT_YN", length=10)
    //private String     vatYn ;

  //  @Column(name="VAT_PERCENT", length=10)
   // private String     vatPercent ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



