/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "TmasDepartmentMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TmasDepartmentMasterId.class)
@Table(name="TMAS_DEPARTMENT_MASTER")


public class TmasDepartmentMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="TMAS_DEPARTMENT_ID", nullable=false)
    private BigDecimal tmasDepartmentId ;

    @Id
    @Column(name="TMAS_PRODUCT_ID", nullable=false)
    private BigDecimal tmasProductId ;

    @Id
    @Column(name="TMAS_STATUS", nullable=false, length=1)
    private String     tmasStatus ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="TMAS_DEPARTMENT_NAME", length=100)
    private String     tmasDepartmentName ;

    @Column(name="CORE_COMPANY_CODE", length=50)
    private String     coreCompanyCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



