/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:38 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import javax.persistence.*;




/**
* Domain class for entity "TmasPfcMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TmasPfcMasterId.class)
@Table(name="TMAS_PFC_MASTER")


public class TmasPfcMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="TMAS_PFC_ID", nullable=false, length=10)
    private String     tmasPfcId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="TMAS_PFC_NAME", length=100)
    private String     tmasPfcName ;

    @Column(name="TMAS_STATUS", length=1)
    private String     tmasStatus ;

    @Column(name="CORE_COMPANY_CODE", length=100)
    private String     coreCompanyCode ;

    @Column(name="PRODUTID", length=10)
    private String     produtid ;

    @Column(name="PATH", length=255)
    private String     path ;

    @Column(name="TYPE", length=255)
    private String     type ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



