/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:31 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "TmasLoginDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TmasLoginDetailsId.class)
@Table(name="TMAS_LOGIN_DETAILS")


public class TmasLoginDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=15)
    private String     loginId ;

    @Id
    @Column(name="PROCESS_ID", nullable=false)
    private BigDecimal processId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="LOGIN_DETAIL_ID")
    private BigDecimal loginDetailId ;

    @Column(name="MENU_IDS", length=500)
    private String     menuIds ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="ACTIVE", length=1)
    private String     active ;

    @Column(name="DEPT_ID")
    private BigDecimal deptId ;

    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Column(name="UNDERWRITTIMG_LIMIT")
    private BigDecimal underwrittimgLimit ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



