/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:42:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:42:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "TmasHomepageMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TmasHomepageMasterId.class)
@Table(name="TMAS_HOMEPAGE_MASTER")


public class TmasHomepageMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="PROCESS_ID", nullable=false)
    private BigDecimal processId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SNO")
    private BigDecimal sno ;

    @Column(name="PRODUCT_ID")
    private BigDecimal productId ;

    @Column(name="DEPT_ID")
    private BigDecimal deptId ;

    @Column(name="PROCESS_NAME", length=100)
    private String     processName ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="ORDER_NO")
    private BigDecimal orderNo ;

    @Column(name="OLD_PRODUCT_ID")
    private BigDecimal oldProductId ;

    @Column(name="UW_LIMIT_YN", length=1)
    private String     uwLimitYn ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



