/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:15 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:44:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "TtrnRiskProposal"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TtrnRiskProposalId.class)
@Table(name="TTRN_RISK_PROPOSAL")


public class TtrnRiskProposal implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="RSK_PROPOSAL_NUMBER", nullable=false, length=50)
    private String     rskProposalNumber ;

    @Id
    @Column(name="RSK_ENDORSEMENT_NO", nullable=false)
    private BigDecimal rskEndorsementNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="RSK_LAYER_NO")
    private BigDecimal rskLayerNo ;

    @Column(name="RSK_LIMIT_OC")
    private BigDecimal rskLimitOc ;

    @Column(name="RSK_LIMIT_DC")
    private BigDecimal rskLimitDc ;

    @Column(name="RSK_LIMIT_OS_OC")
    private BigDecimal rskLimitOsOc ;

    @Column(name="RSK_LIMIT_OS_DC")
    private BigDecimal rskLimitOsDc ;

    @Column(name="RSK_EPI_OFFER_OC")
    private BigDecimal rskEpiOfferOc ;

    @Column(name="RSK_EPI_OFFER_DC")
    private BigDecimal rskEpiOfferDc ;

    @Column(name="RSK_EPI_ESTIMATE")
    private BigDecimal rskEpiEstimate ;

    @Column(name="RSK_EPI_EST_OC")
    private BigDecimal rskEpiEstOc ;

    @Column(name="RSK_EPI_EST_DC")
    private BigDecimal rskEpiEstDc ;

    @Column(name="RSK_XLCOST_OC")
    private BigDecimal rskXlcostOc ;

    @Column(name="RSK_XLCOST_DC")
    private BigDecimal rskXlcostDc ;

    @Column(name="RSK_CEDANT_RETENTION")
    private BigDecimal rskCedantRetention ;

    @Column(name="RSK_SHARE_WRITTEN")
    private BigDecimal rskShareWritten ;

    @Column(name="RSK_SHARE_SIGNED")
    private BigDecimal rskShareSigned ;

    @Column(name="RSK_ADJRATE")
    private BigDecimal rskAdjrate ;

    @Column(name="RSK_EPI_OSOF_OC")
    private BigDecimal rskEpiOsofOc ;

    @Column(name="RSK_EPI_OSOF_DC")
    private BigDecimal rskEpiOsofDc ;

    @Column(name="RSK_EPI_OSOE_OC")
    private BigDecimal rskEpiOsoeOc ;

    @Column(name="RSK_EPI_OSOE_DC")
    private BigDecimal rskEpiOsoeDc ;

    @Column(name="RSK_XLCOST_OS_OC")
    private BigDecimal rskXlcostOsOc ;

    @Column(name="RSK_XLCOST_OS_DC")
    private BigDecimal rskXlcostOsDc ;

    @Column(name="RSK_PF_COVERED", length=50)
    private String     rskPfCovered ;

    @Column(name="RSK_SUBJ_PREMIUM_OC")
    private BigDecimal rskSubjPremiumOc ;

    @Column(name="RSK_SUBJ_PREMIUM_DC")
    private BigDecimal rskSubjPremiumDc ;

    @Column(name="RSK_MAX_LMT_COVER")
    private BigDecimal rskMaxLmtCover ;

    @Column(name="RSK_DEDUC_OC")
    private BigDecimal rskDeducOc ;

    @Column(name="RSK_DEDUC_DC")
    private BigDecimal rskDeducDc ;

    @Column(name="RSK_XLPREM_OC")
    private BigDecimal rskXlpremOc ;

    @Column(name="RSK_XLPREM_DC")
    private BigDecimal rskXlpremDc ;

    @Column(name="RSK_MD_INSTALLMENT_NOS")
    private BigDecimal rskMdInstallmentNos ;

    @Column(name="RSK_MD_PREM_OC")
    private BigDecimal rskMdPremOc ;

    @Column(name="RSK_MD_PREM_DC")
    private BigDecimal rskMdPremDc ;

    @Column(name="RSK_MD_PREM_OS_OC")
    private BigDecimal rskMdPremOsOc ;

    @Column(name="RSK_MD_PREM_OS_DC")
    private BigDecimal rskMdPremOsDc ;

    @Column(name="RSK_XL_COMMON_AC")
    private BigDecimal rskXlCommonAc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_ENTRY_DATE")
    private Date       rskEntryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_END_DATE")
    private Date       rskEndDate ;

    @Column(name="RSK_STATUS", length=1)
    private String     rskStatus ;

    @Column(name="RSK_REMARKS", length=500)
    private String     rskRemarks ;

    @Column(name="RSK_PREMIUM_QUOTA_SHARE")
    private BigDecimal rskPremiumQuotaShare ;

    @Column(name="RSK_PREMIUM_SURPULS")
    private BigDecimal rskPremiumSurpuls ;

    @Column(name="RSK_CEDRET_TYPE", length=1)
    private String     rskCedretType ;

    @Column(name="RSK_SP_RETRO", length=4)
    private String     rskSpRetro ;

    @Column(name="RSK_NO_OF_INSURERS")
    private BigDecimal rskNoOfInsurers ;

    @Column(name="LIMIT_PER_VESSEL_OC")
    private BigDecimal limitPerVesselOc ;

    @Column(name="LIMIT_PER_VESSEL_DC")
    private BigDecimal limitPerVesselDc ;

    @Column(name="LIMIT_PER_LOCATION_OC")
    private BigDecimal limitPerLocationOc ;

    @Column(name="LIMIT_PER_LOCATION_DC")
    private BigDecimal limitPerLocationDc ;

    @Column(name="RSK_PREMIUM_QUOTA_SHARE_DC")
    private BigDecimal rskPremiumQuotaShareDc ;

    @Column(name="RSK_PREMIUM_SURPLUS_DC")
    private BigDecimal rskPremiumSurplusDc ;

    @Column(name="COMM_QS_AMT")
    private BigDecimal commQsAmt ;

    @Column(name="COMM_SURPLUS_AMT")
    private BigDecimal commSurplusAmt ;

    @Column(name="COMM_QS_AMT_DC")
    private BigDecimal commQsAmtDc ;

    @Column(name="COMM_SURPLUS_AMT_DC")
    private BigDecimal commSurplusAmtDc ;

    @Column(name="EGPNI_AS_OFFER")
    private BigDecimal egpniAsOffer ;

    @Column(name="OURASSESSMENT")
    private BigDecimal ourassessment ;

    @Column(name="EGPNI_AS_OFFER_DC")
    private BigDecimal egpniAsOfferDc ;

    @Column(name="RSK_TREATY_SURP_LIMIT_OC")
    private BigDecimal rskTreatySurpLimitOc ;

    @Column(name="RSK_TREATY_SURP_LIMIT_DC")
    private BigDecimal rskTreatySurpLimitDc ;

    @Column(name="RSK_TREATY_SURP_LIMIT_OS_OC")
    private BigDecimal rskTreatySurpLimitOsOc ;

    @Column(name="RSK_TREATY_SURP_LIMIT_OS_DC")
    private BigDecimal rskTreatySurpLimitOsDc ;

    @Column(name="SUB_CLASS")
    private BigDecimal subClass ;

    @Column(name="RSK_EVENT_LIMIT_OC")
    private BigDecimal rskEventLimitOc ;

    @Column(name="RSK_EVENT_LIMIT_DC")
    private BigDecimal rskEventLimitDc ;

    @Column(name="RSK_EVENT_LIMIT_OS_OC")
    private BigDecimal rskEventLimitOsOc ;

    @Column(name="RSK_EVENT_LIMIT_OS_DC")
    private BigDecimal rskEventLimitOsDc ;

    @Column(name="RSK_COVER_LIMIT_UXL_OC")
    private BigDecimal rskCoverLimitUxlOc ;

    @Column(name="RSK_COVER_LIMIT_UXL_DC")
    private BigDecimal rskCoverLimitUxlDc ;

    @Column(name="RSK_COVER_LIMIT_UXL_OS_OC")
    private BigDecimal rskCoverLimitUxlOsOc ;

    @Column(name="RSK_COVER_LIMIT_UXL_OS_DC")
    private BigDecimal rskCoverLimitUxlOsDc ;

    @Column(name="RSK_DEDUCTABLE_UXL_OC")
    private BigDecimal rskDeductableUxlOc ;

    @Column(name="RSK_DEDUCTABLE_UXL_DC")
    private BigDecimal rskDeductableUxlDc ;

    @Column(name="RSK_DEDUCTABLE_UXL_OS_OC")
    private BigDecimal rskDeductableUxlOsOc ;

    @Column(name="RSK_DEDUCTABLE_UXL_OS_DC")
    private BigDecimal rskDeductableUxlOsDc ;

    @Column(name="RSK_PML", length=10)
    private String     rskPml ;

    @Column(name="RSK_PML_PERCENT")
    private BigDecimal rskPmlPercent ;

    @Column(name="RSK_EGNPI_PML_OC")
    private BigDecimal rskEgnpiPmlOc ;

    @Column(name="RSK_EGNPI_PML_DC")
    private BigDecimal rskEgnpiPmlDc ;

    @Column(name="RSK_EGNPI_PML_OS_OC")
    private BigDecimal rskEgnpiPmlOsOc ;

    @Column(name="RSK_EGNPI_PML_OS_DC")
    private BigDecimal rskEgnpiPmlOsDc ;

    @Column(name="RSK_PREMIUM_BASIS", length=10)
    private String     rskPremiumBasis ;

    @Column(name="RSK_MINIMUM_RATE")
    private BigDecimal rskMinimumRate ;

    @Column(name="RSK_MAXIIMUM_RATE")
    private BigDecimal rskMaxiimumRate ;

    @Column(name="RSK_BURNING_COST_LF", length=20)
    private String     rskBurningCostLf ;

    @Column(name="RSK_MINIMUM_PREMIUM_OC")
    private BigDecimal rskMinimumPremiumOc ;

    @Column(name="RSK_MINIMUM_PREMIUM_DC")
    private BigDecimal rskMinimumPremiumDc ;

    @Column(name="RSK_MINIMUM_PREMIUM_OS_OC")
    private BigDecimal rskMinimumPremiumOsOc ;

    @Column(name="RSK_MINIMUM_PREMIUM_OS_DC")
    private BigDecimal rskMinimumPremiumOsDc ;

    @Column(name="RSK_PAYMENT_DUE_DAYS", length=10)
    private String     rskPaymentDueDays ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SYS_DATE")
    private Date       sysDate ;

    @Column(name="RSK_TRTY_LMT_PML_OC", length=100)
    private String     rskTrtyLmtPmlOc ;

    @Column(name="RSK_TRTY_LMT_PML_DC", length=100)
    private String     rskTrtyLmtPmlDc ;

    @Column(name="RSK_TRTY_LMT_PML_OS_OC", length=100)
    private String     rskTrtyLmtPmlOsOc ;

    @Column(name="RSK_TRTY_LMT_PML_OS_DC", length=100)
    private String     rskTrtyLmtPmlOsDc ;

    @Column(name="RSK_TRTY_LMT_SUR_PML_OC", length=100)
    private String     rskTrtyLmtSurPmlOc ;

    @Column(name="RSK_TRTY_LMT_SUR_PML_DC", length=100)
    private String     rskTrtyLmtSurPmlDc ;

    @Column(name="RSK_TRTY_LMT_SUR_PML_OS_OC", length=100)
    private String     rskTrtyLmtSurPmlOsOc ;

    @Column(name="RSK_TRTY_LMT_SUR_PML_OS_DC", length=100)
    private String     rskTrtyLmtSurPmlOsDc ;

    @Column(name="RSK_TRTY_LMT_OURASS_PML_OC", length=100)
    private String     rskTrtyLmtOurassPmlOc ;

    @Column(name="RSK_TRTY_LMT_OURASS_PML_DC", length=100)
    private String     rskTrtyLmtOurassPmlDc ;

    @Column(name="RSK_TRTY_LMT_OURASS_PML_OS_OC", length=100)
    private String     rskTrtyLmtOurassPmlOsOc ;

    @Column(name="RSK_TRTY_LMTOUR_ASS_PML_OS_DC", length=100)
    private String     rskTrtyLmtourAssPmlOsDc ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



