/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:13 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:44:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "TtrnRiskCommission"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(TtrnRiskCommissionId.class)
@Table(name="TTRN_RISK_COMMISSION")


public class TtrnRiskCommission implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="RSK_PROPOSAL_NUMBER", nullable=false, length=35)
    private String     rskProposalNumber ;

    @Id
    @Column(name="RSK_ENDORSEMENT_NO", nullable=false)
    private BigDecimal rskEndorsementNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="RSK_LAYER_NO")
    private BigDecimal rskLayerNo ;

    @Column(name="RSK_BROKERAGE")
    private BigDecimal rskBrokerage ;

    @Column(name="RSK_TAX")
    private BigDecimal rskTax ;

    @Column(name="RSK_PROFIT_COMM")
    private BigDecimal rskProfitComm ;

    @Column(name="RSK_RESERVE_ON_LOSS")
    private BigDecimal rskReserveOnLoss ;

    @Column(name="RSK_ACQUISTION_COST_OC")
    private BigDecimal rskAcquistionCostOc ;

    @Column(name="RSK_ACQUISTION_COST_DC")
    private BigDecimal rskAcquistionCostDc ;

    @Column(name="RSK_COMM_QUOTASHARE")
    private BigDecimal rskCommQuotashare ;

    @Column(name="RSK_COMM_SURPLUS")
    private BigDecimal rskCommSurplus ;

    @Column(name="RSK_OVERRIDER_PERC")
    private BigDecimal rskOverriderPerc ;

    @Column(name="RSK_MANAGEMENT_EXPENSES")
    private BigDecimal rskManagementExpenses ;

    @Column(name="RSK_LOSS_CARRYFORWARD", length=500)
    private String     rskLossCarryforward ;

    @Column(name="RSK_PREMIUM_RESERVE")
    private BigDecimal rskPremiumReserve ;

    @Column(name="RSK_LOSS_RESERVE")
    private BigDecimal rskLossReserve ;

    @Column(name="RSK_INTEREST")
    private BigDecimal rskInterest ;

    @Column(name="RSK_PF_INOUT_PREM")
    private BigDecimal rskPfInoutPrem ;

    @Column(name="RSK_PF_INOUT_LOSS")
    private BigDecimal rskPfInoutLoss ;

    @Column(name="RSK_LOSSADVICE", length=500)
    private String     rskLossadvice ;

    @Column(name="RSK_CASHLOSS_LMT_OC")
    private BigDecimal rskCashlossLmtOc ;

    @Column(name="RSK_CASHLOSS_LMT_DC")
    private BigDecimal rskCashlossLmtDc ;

    @Column(name="RSK_AGGREGATE_LIAB_OC")
    private BigDecimal rskAggregateLiabOc ;

    @Column(name="RSK_AGGREGATE_LIAB_DC")
    private BigDecimal rskAggregateLiabDc ;

    @Column(name="RSK_REINSTATE_NO")
    private BigDecimal rskReinstateNo ;

    @Column(name="RSK_REINSTATE_ADDL_PREM_OC")
    private BigDecimal rskReinstateAddlPremOc ;

    @Column(name="RSK_REINSTATE_ADDL_PREM_DC")
    private BigDecimal rskReinstateAddlPremDc ;

    @Column(name="RSK_LEAD_UW", length=500)
    private String     rskLeadUw ;

    @Column(name="RSK_LEAD_UW_SHARE")
    private BigDecimal rskLeadUwShare ;

    @Column(name="RSK_ACCOUNTS", length=500)
    private String     rskAccounts ;

    @Column(name="RSK_EXCLUSION", length=500)
    private String     rskExclusion ;

    @Column(name="RSK_REMARKS", length=500)
    private String     rskRemarks ;

    @Column(name="RSK_UW_RECOMM", length=500)
    private String     rskUwRecomm ;

    @Column(name="RSK_GM_APPROVAL", length=500)
    private String     rskGmApproval ;

    @Column(name="RSK_DECISION", length=500)
    private String     rskDecision ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_ENTRY_DATE")
    private Date       rskEntryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RSK_END_DATE")
    private Date       rskEndDate ;

    @Column(name="RSK_STATUS", length=5)
    private String     rskStatus ;

    @Column(name="RSK_COMM")
    private BigDecimal rskComm ;

    @Column(name="RSK_LOSS_RECORD", length=100)
    private String     rskLossRecord ;

    @Column(name="RSK_DGM_APPROVAL", length=100)
    private String     rskDgmApproval ;

    @Column(name="RSK_UNDERWRITTER_CODE", length=100)
    private String     rskUnderwritterCode ;

    @Column(name="RSK_UW_RECOMMENDATION", length=100)
    private String     rskUwRecommendation ;

    @Column(name="RSK_OTH_ACCEP", length=100)
    private String     rskOthAccep ;

    @Column(name="RSK_REF_TO_HO", length=100)
    private String     rskRefToHo ;

    @Column(name="RSK_SHARE_PROFIT_COMMISSION", length=500)
    private String     rskShareProfitCommission ;

    @Column(name="RSK_OTHER_COST")
    private BigDecimal rskOtherCost ;

    @Column(name="RSK_REINSTATE_ADDL_PREM_PCT")
    private BigDecimal rskReinstateAddlPremPct ;

    @Column(name="RSK_BURNING_COST_PCT")
    private BigDecimal rskBurningCostPct ;

    @Column(name="RSK_AGGREGATE_DEDUCT_OC")
    private BigDecimal rskAggregateDeductOc ;

    @Column(name="RSK_AGGREGATE_DEDUCT_DC")
    private BigDecimal rskAggregateDeductDc ;

    @Column(name="RSK_NOCLAIMBONUS_PRCENT")
    private BigDecimal rskNoclaimbonusPrcent ;

    @Column(name="RSK_BONUS_ID", length=50)
    private String     rskBonusId ;

    @Column(name="RSK_CREASTA_STATUS", length=10)
    private String     rskCreastaStatus ;

    @Column(name="RSK_EVENT_LIMIT_OC")
    private BigDecimal rskEventLimitOc ;

    @Column(name="RSK_EVENT_LIMIT_DC")
    private BigDecimal rskEventLimitDc ;

    @Column(name="RSK_AGGREGATE_LIMIT_OC")
    private BigDecimal rskAggregateLimitOc ;

    @Column(name="RSK_AGGREGATE_LIMIT_DC")
    private BigDecimal rskAggregateLimitDc ;

    @Column(name="RSK_OCCURRENT_LIMIT_OC")
    private BigDecimal rskOccurrentLimitOc ;

    @Column(name="RSK_OCCURRENT_LIMIT_DC")
    private BigDecimal rskOccurrentLimitDc ;

    @Column(name="RSK_SLADSCALE_COMM", length=10)
    private String     rskSladscaleComm ;

    @Column(name="RSK_LOSS_PART_CARRIDOR", length=10)
    private String     rskLossPartCarridor ;

    @Column(name="RSK_COMBIN_SUB_CLASS", length=10)
    private String     rskCombinSubClass ;

    @Column(name="SUB_CLASS")
    private BigDecimal subClass ;

    @Column(name="RSK_REINSTATEMENT_PREMIUM", length=20)
    private String     rskReinstatementPremium ;

    @Column(name="RSK_PAYEMENT_DUE_DAY", length=20)
    private String     rskPayementDueDay ;

    @Column(name="RSK_LEAD_UNDERWRITER_COUNTRY", length=500)
    private String     rskLeadUnderwriterCountry ;

    @Column(name="RSK_TOTAL_NO_REINSTATEMENTS", length=20)
    private String     rskTotalNoReinstatements ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SYS_DATE")
    private Date       sysDate ;

    @Column(name="RSK_INCLUDE_ACQ_COST", length=100)
    private String     rskIncludeAcqCost ;

    @Column(name="RSK_OUR_ASS_ACQ_COST", length=100)
    private String     rskOurAssAcqCost ;

    @Column(name="RSK_OUR_ACQ_OUR_SHARE_OC", length=100)
    private String     rskOurAcqOurShareOc ;

    @Column(name="RSK_CRESTA_COMBIN_SUB_CLASS", length=10)
    private String     rskCrestaCombinSubClass ;

    @Column(name="RSK_SLIDE_COMBIN_SUB_CLASS", length=10)
    private String     rskSlideCombinSubClass ;

    @Column(name="RSK_LOSS_COMBIN_SUB_CLASS", length=10)
    private String     rskLossCombinSubClass ;

    @Column(name="RSK_PRO_MANAGEMENT_EXP")
    private BigDecimal rskProManagementExp ;

    @Column(name="RSK_PRO_COMM_TYPE", length=10)
    private String     rskProCommType ;

    @Column(name="RSK_PRO_COMM_PER")
    private BigDecimal rskProCommPer ;

    @Column(name="RSK_PRO_SET_UP", length=10)
    private String     rskProSetUp ;

    @Column(name="RSK_PRO_SUP_PRO_COM", length=10)
    private String     rskProSupProCom ;

    @Column(name="RSK_PRO_LOSS_CARY_TYPE", length=10)
    private String     rskProLossCaryType ;

    @Column(name="RSK_PRO_LOSS_CARY_YEAR", length=10)
    private String     rskProLossCaryYear ;

    @Column(name="RSK_PRO_PROFIT_CARY_TYPE", length=10)
    private String     rskProProfitCaryType ;

    @Column(name="RSK_PRO_PROFIT_CARY_YEAR", length=10)
    private String     rskProProfitCaryYear ;

    @Column(name="RSK_PRO_FIRST_PFO_COM")
    private BigDecimal rskProFirstPfoCom ;

    @Column(name="RSK_PRO_FIRST_PFO_COM_PRD", length=10)
    private String     rskProFirstPfoComPrd ;

    @Column(name="RSK_PRO_SUB_PFO_COM_PRD", length=10)
    private String     rskProSubPfoComPrd ;

    @Column(name="RSK_PRO_SUB_PFO_COM")
    private BigDecimal rskProSubPfoCom ;

    @Column(name="RSK_PRO_SUB_SEQ_CAL", length=10)
    private String     rskProSubSeqCal ;

    @Column(name="RSK_PRO_NOTES", length=2000)
    private String     rskProNotes ;

    @Column(name="RSK_DOC_STATUS", length=20)
    private String     rskDocStatus ;

    @Column(name="RSK_COMMISSION_QS_YN", length=10)
    private String     rskCommissionQsYn ;

    @Column(name="RSK_COMMISSION_SUR_YN", length=10)
    private String     rskCommissionSurYn ;

    @Column(name="RSK_OVERRIDE_YN", length=10)
    private String     rskOverrideYn ;

    @Column(name="RSK_BROKARAGE_YN", length=10)
    private String     rskBrokarageYn ;

    @Column(name="RSK_TAX_YN", length=10)
    private String     rskTaxYn ;

    @Column(name="RSK_OTHER_COST_YN", length=10)
    private String     rskOtherCostYn ;

    @Column(name="RSK_CEED_ODI_YN", length=10)
    private String     rskCeedOdiYn ;

    @Column(name="RSK_RATE", length=3)
    private String     rskRate ;

    @Column(name="RSK_COMMISSION_TYPE", length=10)
    private String     rskCommissionType ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



