/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-15 ( Date ISO 2022-09-15 - Time 15:44:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-15 ( 15:44:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.insurance.model.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import javax.persistence.*;




/**
* Domain class for entity "UnderwritterMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(UnderwritterMasterId.class)
@Table(name="UNDERWRITTER_MASTER")


public class UnderwritterMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="UWR_CODE", nullable=false, length=10)
    private String     uwrCode ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="UNDERWRITTER", length=30)
    private String     underwritter ;

    @Column(name="UWR_STATUS", length=1)
    private String     uwrStatus ;

    @Column(name="CORE_COMPANY_CODE", length=20)
    private String     coreCompanyCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



